### ISSUE TITLE
☂️ Improve Orbit reboot components tests coverage

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#497]
## Description

To speed up the delivery of the reboot of Orbit we omited Jest interaction tests for a few components. This issue aims to pay this debt.

## Specifications

All overlay components have a test suite of Jest interaction tests.

## Related issues

- [x] Overlay utilities (https://github.com/gsoft-inc/sg-orbit/issues/501)
- [x] Tooltip (https://github.com/gsoft-inc/sg-orbit/issues/504)
- [x] Select (https://github.com/gsoft-inc/sg-orbit/issues/503)
- [x] Popover (https://github.com/gsoft-inc/sg-orbit/issues/502)
- [x] Menu (https://github.com/gsoft-inc/sg-orbit/issues/500)
- [x] Listbox (https://github.com/gsoft-inc/sg-orbit/issues/499)
- [x] DateInput (https://github.com/gsoft-inc/sg-orbit/issues/498)
- [x] Autocomplete (https://github.com/gsoft-inc/sg-orbit/issues/576)
