### ISSUE TITLE
☂️ InputGroup component

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#517]
## Description

We would like to have the ability to attach prefix/suffix or other components like a `Menu` to input elements.

Something similar to [React Bootstrap Input Group](https://react-bootstrap.github.io/components/input-group/) component.

We already have a usecase in Apricot:

![image](https://user-images.githubusercontent.com/794579/115418059-29fde100-a1c7-11eb-9832-040968e01b58.png)

And it would also improve the presets feature of our `<DateRangeInput>` component:

![image](https://user-images.githubusercontent.com/794579/115418195-4d289080-a1c7-11eb-9f48-a0be32c35a83.png)

For the presets, it could be similare to the Buttons with Dropdowns example of React Bootstrap:

![image](https://user-images.githubusercontent.com/794579/115418356-6d584f80-a1c7-11eb-8436-b8d4096a552a.png)

## Specifications

- Can wrap  a `<TextInput>`, `<NumberInput>`, `<PasswordInput>`, `<SearchInput>`, `<DateInput>` and `<DateRangeInput>`.
- Support a **single** prefix and/or suffix.
- A prefix or a suffix can be textual or an overlay component like `<Menu>`, `<Select`>, `<Popover>`.
- In case of an overlay component, the consumer is fully responsabile of providing a trigger which match the style he/she is looking to achieve.
- The focus ring should never render on the whole group. If the prefix/suffix are focusable, the focus should shift from prefix, to input then suffix.

![image](https://user-images.githubusercontent.com/794579/115420158-e6a47200-a1c8-11eb-904d-42b438a94c99.png)

- The focus ring rules also applies to hover state.
- Must work with Orbit forms/fields

## Related issues

- [x] Define component use cases & specifications
- [x] Design component in Figma (https://github.com/gsoft-inc/sg-orbit/issues/604)
- [ ] Code component (https://github.com/gsoft-inc/sg-orbit/issues/571)
