### ISSUE TITLE
☂️ Reboot debt

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#521]
## Description

To speed up Orbit reboot development and match the expected release date we skip a bunch of important tasks. We accumulated a lot of debt, mostly technical debt. This issue aims to give visibility on the progress of the important debt issues.

## Related issues

- [x] Component tests (https://github.com/gsoft-inc/sg-orbit/issues/497)
- [x] TypeScript support (https://github.com/gsoft-inc/sg-orbit/issues/516)
- [x] Fix focus ring for overlay components (https://github.com/gsoft-inc/sg-orbit/issues/512)
- [x] Deprecate Calibre (https://github.com/gsoft-inc/sg-orbit/issues/534)
- [x] Update Figma (https://github.com/gsoft-inc/sg-orbit/issues/560)
