### ISSUE TITLE
☂️ Help Apricot bring dark mode to a reality

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#526]
## Design Principles

Design for humans & Make it memorable

## Description

We are in 2021, most IT professionals expect products to offer a dark mode. Orbit reboot added an option to choose between a `light` or `dark` color scheme for Orbit components.

This issue aims to extend our color scheme feature to our styles foundation.

## Related issues

- [x] Adapt ShareGate colors to match WCAG contrast specifications (https://github.com/gsoft-inc/sg-orbit/issues/525)
- [x] Define semantic CSS properties for colors
- [x] Provide CSS semantic classes
- [ ] Train Apricot frontend developers about the new CSS semantic classes
- [x] https://github.com/gsoft-inc/sg-orbit/issues/706#issue-949087010
