### ISSUE TITLE
☂️ Implement missing atom components

### ISSUE THREAD

**Issue by patricklafrance** [gsoft-inc/sg-orbit#565]
## Description

Orbit reboot still miss a few atoms components which we haven't released yet because we currently have a suitable solution in Apricot.

However, even if they are suitable for now they doesn't match our specs, doesn't enforce any standardisation and we cannot built any Orbit components of top of them until they are part of Orbit.

## Related issues

- [x] Input group (https://github.com/gsoft-inc/sg-orbit/issues/517)
- [ ] Modal (https://github.com/gsoft-inc/sg-orbit/issues/530)
- [ ] Alert dialog (https://github.com/gsoft-inc/sg-orbit/issues/531)
- [x] Avatar (https://github.com/gsoft-inc/sg-orbit/issues/535)
